name: Deploy content to Production

on:
  push:
    branches: ['release/latest']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: 'https://${{ secrets.BACKEND_HOST_PROD }}/api/v1'
      REACT_APP_BASE_URL: 'https://${{ secrets.BACKEND_HOST_PROD }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_CREDENTIALS }}" >> ~/.npmrc

      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy with rsync to Production
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude '.git' --exclude '.github' --exclude 'cypress'
          path: build/
          remote_path: ${{ secrets.DEPLOY_DOC_ROOT_PROD }}
          remote_host: ${{ secrets.DEPLOY_HOST_PROD }}
          remote_user: ${{ secrets.DEPLOY_USER_PROD }}
          remote_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY_PROD }}
